name: model
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Naoto Higuchi <email@example.com>

environment:
  sdk: ">=2.0.0-dev.43.0 <2.0.0"

dependencies:
  http:

dev_dependencies:
  test: ^0.12.0
