name: angular_hn
environment:
  sdk: ">=2.0.0-dev.46.0 <2.0.0"

dependencies:
  angular: ^5.0.0-alpha+10
  angular_router: ^2.0.0-alpha+10
  model: 
    path: ../model

dev_dependencies:
  build_runner: ^0.8.2
  build_test: ^0.10.1+1
  build_web_compilers: ^0.3.6
